//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        public int IdCredito { get; set; }
        public int IdPago { get; set; }
        public int IdCliente { get; set; }
        public int CuotasC { get; set; }
        public System.DateTime FechaP { get; set; }
        public double CapitalC { get; set; }
        public int Intereses { get; set; }
        public int IdReporte { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Credito Credito { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
